# Generating Same Random Number with Seed Function

In [17]:
import numpy as np

In [18]:
arr = np.random.randint(1,101,10)
arr

array([76, 75,  1, 77, 14, 83, 90, 36, 63, 36])

In [19]:
# seed() generates same random numbers at different engines/machines

np.random.seed(12)
arr = np.random.randint(1,101,15)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35])

In [20]:
# counting size of array

arr.size

15

In [21]:
# checking shape of array

arr.shape

(15,)

In [27]:
# checking type of array

arr.ndim

2

In [28]:
# rehsaping '1-d' array into '2-d' array
np.random.seed(12)
arr = np.random.randint(1,101,15).reshape(3,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [24]:
arr.size

15

In [25]:
arr.ndim

2

In [26]:
arr.shape

(3, 5)