# Indexing & Slicing in 2-D Array in NumPy

## 1: Create 2-D Array

In [1]:
import numpy as np

In [3]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## 2: Indexing

###    2.1: Indexing using double bracket notation

In [7]:
# This will display array 0, index 1 i.e. 10 using double bracket notation

matrix[0][1]

10

In [8]:
# This will display array 1, index 1 i.e. 25

matrix[1][1]

25

### 2.2: Indexing using single bracket notation (Recommended)

In [9]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
# This will display array 0, index 1 i.e. 10 using single bracket notation

matrix[0,1]

10

In [13]:
# This will display array 1, index 1 i.e. 25 using single bracket notation

matrix[1,1]

25

## 3: Slicing

### 3.1: Slicing using single bracket notation

In [16]:
# This will slice row 0 and row 1 with all columns

matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [19]:
# This will slice row 0 & row 1 but only with first two columns of both rows

matrix[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [20]:
# This will slice row 1 & row 2 with column 2 & 3 only

matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [36]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)

In [37]:
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [38]:
matrix2.size

25

In [39]:
matrix2.ndim

2

In [40]:
matrix2.shape

(5, 5)

In [42]:
# This will slice rows having index 2 & 3 and columns having index of 1 to 3

#  output should be ([[33,47,97],
#                   [79,37,97]])

matrix2[2:4,1:4]

array([[33, 47, 97],
       [79, 37, 97]])

In [45]:
# This will slice rows having index 1 to 3 and columns having index of 1 to 3

#  output should be ([[87,98,97],
#                     [33,47,97],
#                     [79,37,97]])
 
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [48]:
# This will slice rows having index 2 to last and columns having index of 2 to last index

#  output should be ([[47,97,26],
#                     [37,97,81],
#                     [56,68, 3]])

matrix2[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])