# Practicing NumPy Library

In [1]:
import numpy as np

In [2]:
nums = [1,2,3]

In [3]:
# making 1-D array. 1-D array is called 'Vector'
nums = np.array(nums)

In [4]:
nums

array([1, 2, 3])

In [5]:
# making 2-D Array. 2-D Array is called 'Matrix'
nums = ([1,2,3],[4,5,6])
nums=np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# making 3-D Array. 3-D Array is called 'Tensor'
nums = (([1,2,3],[4,5,6]),([1,2,3],[4,5,6]))
nums=np.array(nums)
nums

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
# to check type of array. This will return '3' to show that it is 3-D array.
nums.ndim

3

In [8]:
# making 2-D Array. 2-D Array is called 'Matrix'
nums = ([1,2,3],[4,5,6])
nums=np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#  this will display 'shape' of array i.e 2 rows & 3 columns.
nums.shape

(2, 3)

In [10]:
# this will show 'data-type' of array
nums.dtype

dtype('int32')

## Practicing Some Functions of NumPy

### 'Zeros' Function

In [11]:
#  we'll create an array named 'arr' and practice varous functions of NumPy library
arr = np.zeros(5)   # this will return '1-D' array with each column of zeros
arr

array([0., 0., 0., 0., 0.])

In [12]:
# this will create a 2-D array of 2 rows & 3 columns with each element as zero
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

### 'Ones' Function

In [13]:
# this will create an array with 'ones' function. It will create a 1-D array with each 1-row and 3-columns as zeros
arr = np.ones(3)
arr

array([1., 1., 1.])

In [14]:
# this will create a 2-D array with 2 rows, 3 columns having each element as 'ones'
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr.ndim

2

### 'Eye' Function

In [16]:
# This will create an array using 'eye' function.
# This will create '2-D' array with 'ones' as diagnal and rest with 'zeros'
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr.ndim

2

In [18]:
# This will create 2-D array with 3 rows, 4 columns having 'ones' as diagnal elements and 'zeros' as rest all
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
arr.ndim

2

In [20]:
# checking diagnal elements of an array
np.diag(arr)

array([1., 1., 1.])

### 'diag' Function

In [21]:
# this will create a 'square matrix' mean 2-D array with diagnal elements as passed in arguements

arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
arr.ndim

2

In [23]:
# to check diagnal of an array

np.diag(arr)

array([1, 2, 3, 4])

### 'randint' Function

In [24]:
# Here we will generate random integers by using 'randint' function

# here '1' is minimum number (it may be inclusive), '15' is maximum number (this will be exclusive) and . . . 
# '4' is the no of required integers

rand_arr = np.random.randint(1,15,4)
rand_arr

array([ 1,  5, 14, 14])

In [25]:
# this will generate any random integer less than one number as passed in as arguement

# here this will generate any random integer from '0' to '3'
rand_arr = np.random.randint(4)
rand_arr

1

### 'rand' function

In [26]:
# this function will generate random float numbers upto given 'arguements' with zero as whole number

rand_arr = np.random.rand(3)
rand_arr

array([0.04725012, 0.11943714, 0.67751104])

In [27]:
# this will generate 2-D array of random float numbers with 2 rows, & 3 columns
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.82368635, 0.399064  , 0.49281418],
       [0.10947738, 0.53862918, 0.29297628]])

In [28]:
rand_arr.ndim

2

### 'randn' Function

In [29]:
# this will create random float numbers with 'zero' as 'centered'
# this mean that these numbers may be positive or negative

rand_arr = np.random.randn(14)
rand_arr

array([-0.97384789, -0.97761822,  0.17207634, -0.62846668, -0.47281204,
       -0.36840953,  1.62816095,  0.40269728, -2.33295617,  0.65684518,
       -0.7069162 ,  1.17834211,  0.19180003,  0.38406922])

In [30]:
# this will calculate mean of an array

np.mean(rand_arr)

-0.13193111613173097

In [31]:
# this will calculate 'mean' of '50' random float numbers
rand_arr = np.random.randn(50)
np.mean(rand_arr)

-0.04874186786820103

# Reshaping of Data

In [32]:
# this will generate 20 random integers whose min number may be 1 and max number may be 39 (max num - 1)

arr = np.random.randint(1,40,20)
arr

array([ 2, 18, 32,  1, 20, 33, 34, 10,  3, 19, 14, 10, 34, 34,  7, 39, 16,
       18,  8,  6])

In [33]:
# This displays that it is a '1-D' array mean a 'Vector'

arr.ndim

1

In [34]:
# this will display that it is a 1-D array (Vector) with 20 elements
arr.shape

(20,)

## Reshaping into 2-D array

In [35]:
# This will reshape an existing array
# Here first arguement is type of required array, mean '2-D' array & second arguement (i.e. 10) shows the maximum number 
# of previously generated array of 20 numbers mean 2 x 10 = 20 (which was max number of array)

arr = arr.reshape(2,10)
arr

array([[ 2, 18, 32,  1, 20, 33, 34, 10,  3, 19],
       [14, 10, 34, 34,  7, 39, 16, 18,  8,  6]])

In [36]:
# further elaboration of a/q array. here '1-d' array of 20 numbers is reshaped in '2-d' array of 2 rows & 4 columns

arr = arr.reshape(4,5)
arr

array([[ 2, 18, 32,  1, 20],
       [33, 34, 10,  3, 19],
       [14, 10, 34, 34,  7],
       [39, 16, 18,  8,  6]])

In [37]:
arr.ndim

2

In [38]:
arr.shape

(4, 5)

In [39]:
# another reshaping of array with 10 rows and 2 columns

arr = arr.reshape(10,2)
arr

array([[ 2, 18],
       [32,  1],
       [20, 33],
       [34, 10],
       [ 3, 19],
       [14, 10],
       [34, 34],
       [ 7, 39],
       [16, 18],
       [ 8,  6]])

## Reshaping into 3-D array

In [40]:
# This will reshape the existing array into '3-D' array

arr = arr.reshape(2,2,5)
arr

array([[[ 2, 18, 32,  1, 20],
        [33, 34, 10,  3, 19]],

       [[14, 10, 34, 34,  7],
        [39, 16, 18,  8,  6]]])

In [41]:
arr.ndim

3

In [42]:
arr.shape

(2, 2, 5)

## What is -1 in "Reshape" function in NumPy

In [43]:
# this will create a '1-d' array of starting from first arguement i.e. '1', ending at 'last arguement - 1' i.e. (11-1=10)

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# checking type of array

arr.ndim

1

In [45]:
# checking shape of array
arr.shape    # output will be (10,) mean '1-d' array with 10 elements

(10,)

### This will reshape existing "1-D" array into "2-D" array

In [46]:
arr = arr.reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
# checking type of array

arr.ndim   # output will show that it is '2-d' array

2

In [48]:
# checking shape of array

arr.shape  # output will show that it is a 'square matrix' i.e. '2-d' array with 2 rows & 3 columns

(2, 5)

### Reshaping with second arguement as "Negative Number"

In [49]:
arr = arr.reshape(2,-1)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
arr.ndim

2

In [51]:
arr.shape

(2, 5)

In [52]:
# another presentation of reshaping with "Negative Number"

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# arguement with '-1' negative one is used to auto - calculate the row or column at which position it is used

arr = arr.reshape(5,-1)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [54]:
arr.ndim

2

In [55]:
arr.shape

(5, 2)

In [56]:
# checking size of an array

arr.size

10

In [64]:
# This is a '1-d' array with 110 elements from 1 ~ 110

arr = np.arange(1,111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [65]:
arr.size

110

In [66]:
arr.ndim

1

In [67]:
arr.shape

(110,)

In [69]:
arr = arr.reshape(2,-1)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
         69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
         82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
         95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110]])

In [70]:
arr.ndim

2

In [71]:
arr.shape

(2, 55)

In [86]:
arr = arr.reshape(-1,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [84]:
arr.ndim

2

In [87]:
arr.shape

(11, 10)

In [88]:
arr.size

110