# View Vs Copy in NumPy

## 1:  View

In [33]:
import numpy as np

In [34]:
arr = np.array([5,10,15,20,25,30])

In [35]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [36]:
# this will make a 'view' of varialbe 'arr' in newly created variable 'sliced_array'

sliced_array = arr[2:5]

In [37]:
sliced_array

array([15, 20, 25])

In [38]:
# this will change the indexed values of 'sliced_array' into '0' and this change will also affect the original variable
#  i.e. 'arr'

sliced_array[1:] = 0

In [39]:
sliced_array

array([15,  0,  0])

In [40]:
# index 3 & 4 has been changed into '0' due to change in view 'sliced_array'

arr

array([ 5, 10, 15,  0,  0, 30])

## 2: Copy

In [41]:
arr = np.array([5,10,15,20,25,30])

In [42]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [43]:
# This will make a copy of 'arr' into 'sliced_array'

sliced_array = arr[2:5].copy()

In [44]:
sliced_array

array([15, 20, 25])

In [45]:
# This will change the values of index 1 till last in 'sliced_array' but will have no affect on original variable
# i.e. 'arr' because 'sliced_array' is a copy of 'arr' and not the 'view'

sliced_array[1:] = 0

In [46]:
# index 1 & 2 of 'sliced_array' has been converted into '0'

sliced_array

array([15,  0,  0])

In [47]:
# Change in 'sliced_array' has not affected the variable 'arr' as 'slieced_array' is an independent copy of 'arr' and not
# a 'view' of varialbe 'arr'

arr

array([ 5, 10, 15, 20, 25, 30])