# Conditional Selection in NumPy

In [30]:
import numpy as np

In [31]:
# making an array of size 10 starting from no.1

arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Performing Selection on Array

In [33]:
# This will display 'Ture' by matching each value where it is greater than 5 and otherwise 'False' 

arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
# Assigning values which are greater than '5' of 'arr' to a new variable 'mask'

mask = arr>5

In [35]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [36]:
# Selection of those values of 'arr' which are less than 4

arr[arr<4]

array([1, 2, 3])

In [37]:
# selection of values of 'arr' which are even numbers

arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [38]:
# selection of those values of 'arr' equal to 5

arr[arr==5]

array([5])

In [39]:
# Selection of even numbers of array 'arr' and then conversion of those numbers to 'zeros'

arr[arr%2==0] = 0

In [40]:
# even values of array 'arr' have been converted into 'zeros'

arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])