# Indexing & Slicing of 1-D Array in NumPy

## Indexing

In [2]:
import numpy as np

In [3]:
# Create a '1-D' array

arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [4]:
# printing Index Positions with positive index numbers

print(arr[0])   # output =  5
print(arr[1])   # output = 10
print(arr[2])   # output = 15
print(arr[3])   # output = 20
print(arr[4])   # output = 25

5
10
15
20
25


In [5]:
# this will generate error as there is no value stored at index no.5

arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
# index        -5,-4,-3,-2,-1          
arr = np.array([5,10,15,20,25])
# index         0, 2, 3, 4, 5

arr

In [ ]:
# printing Index Positions with negative index numbers

print(arr[-5])   # output =  5
print(arr[-4])   # output = 10
print(arr[-3])   # output = 15
print(arr[-2])   # output = 20
print(arr[-1])   # output = 25

## Slicing

In [9]:
# index         -5,-4,-3,-2,-1
arr = np.array([10,20,30,40,50])
# index         0, 1, 2, 3, 4

arr

array([10, 20, 30, 40, 50])

In [ ]:
# this will display all elements of array

arr[:]

In [7]:
# This will display all elements of array from index 0 to index 2 (index 3 - 1)

arr[:3]

array([ 5, 10, 15])

In [10]:
# This will display from start to end point of array with 2 step. It will output 10, 30, 50

arr[::2]

array([10, 30, 50])

In [12]:
# this will display using start point as first negative index i.e. -5 upto last point with positive step 1

arr[-5::1]

array([10, 20, 30, 40, 50])

In [14]:
# this will display all elements in reverse order using step as -1

arr[::-1]

array([50, 40, 30, 20, 10])

In [17]:
# This will display all elements except last as stop element is given as '-1' in arguement which exclusive
arr[-5:-1:1]

array([10, 20, 30, 40])